

export interface Dish {
  id: number;
  name: string;
  category: 'soups' | 'main' | 'salads' | 'drinks' | 'desserts';
  price: number;
  image: string;
  description: string;
  available: boolean;
}

export interface CartItem {
  dish: Dish;
  quantity: number;
}

export interface UserProfile {
  id: string; // UUID from Supabase Auth
  full_name: string;
  phone: string;
  address: string;
  role: 'admin' | 'user';
}

export interface Courier {
  id: number;
  name: string;
  phone: string;
  vehicle: string;
  status: 'available' | 'busy' | 'offline';
}

export interface Order {
  id: number;
  user_id?: string;
  created_at: string;
  items: CartItem[]; // Stored as JSONB in DB
  total_amount: number;
  status: 'pending' | 'confirmed' | 'cooking' | 'delivering' | 'delivered' | 'cancelled';
  delivery_address: string;
  contact_phone: string;
  comment?: string;
  payment_method: 'card' | 'cash';
  payment_status: 'pending' | 'succeeded' | 'failed';
  assigned_courier_id?: number;
  is_rated?: boolean;

  // Compatibility fields for mock data
  total?: number;
  address?: string;
  phone?: string;
  date?: string;
}

/* 
  === SUPABASE SQL SCHEMA GUIDE (IMPORTANT) ===
  Выполните это в SQL Editor вашего Supabase проекта:

  -- 1. Таблица блюд
  create table dishes (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    price numeric not null,
    image text,
    description text,
    available boolean default true
  );

  -- 2. Таблица профилей
  create table profiles (
    id uuid references auth.users on delete cascade primary key,
    full_name text,
    phone text,
    address text,
    role text default 'user'
  );

  -- 3. Таблица заказов
  create table orders (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    items jsonb not null,
    total_amount numeric not null,
    status text default 'pending',
    delivery_address text not null,
    contact_phone text not null,
    comment text,
    payment_method text default 'card',
    payment_status text default 'pending'
  );

  -- 4. НАСТРОЙКА БЕЗОПАСНОСТИ (RLS) -- БЕЗ ЭТОГО РАБОТАТЬ НЕ БУДЕТ
  
  -- Разрешить всем видеть блюда
  alter table dishes enable row level security;
  create policy "Allow public read" on dishes for select using (true);
  
  -- Разрешить пользователям создавать свои профили и видеть их
  alter table profiles enable row level security;
  create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
  create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
  create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

  -- Разрешить пользователям создавать заказы и видеть только свои
  alter table orders enable row level security;
  create policy "Users can create orders" on orders for insert with check (auth.uid() = user_id);
  create policy "Users can view own orders" on orders for select using (auth.uid() = user_id);

  -- Админские права (пример: обновить роль вручную через SQL для своего ID)
  -- update profiles set role = 'admin' where id = 'ВАШ_UUID_ИЗ_AUTH';
*/
