
export interface Dish {
  id: number;
  name: string;
  category: 'soups' | 'main' | 'salads' | 'drinks' | 'desserts';
  price: number;
  image: string;
  description: string;
  available: boolean;
}

export interface CartItem {
  dish: Dish;
  quantity: number;
}

export interface UserProfile {
  id: string; // UUID from Supabase Auth
  full_name: string;
  phone: string;
  address: string;
  role: 'admin' | 'user';
}

export interface Courier {
  id: number;
  name: string;
  phone: string;
  vehicle: string;
  status: 'available' | 'busy' | 'offline';
}

export interface Order {
  id: number;
  user_id?: string;
  created_at: string;
  items: CartItem[]; // Stored as JSONB in DB
  total_amount: number;
  status: 'pending' | 'confirmed' | 'cooking' | 'delivering' | 'delivered' | 'cancelled';
  delivery_address: string;
  contact_phone: string;
  comment?: string;
  payment_method: 'card' | 'cash';
  payment_status: 'pending' | 'succeeded' | 'failed';
  assigned_courier_id?: number;
  is_rated?: boolean;

  // Compatibility fields for mock data
  total?: number;
  address?: string;
  phone?: string;
  date?: string;
}

/* 
  === SUPABASE SQL SCHEMA GUIDE ===
  Run this in your Supabase SQL Editor to set up the DB:

  -- 1. Dishes Table
  create table dishes (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    price numeric not null,
    image text,
    description text,
    available boolean default true
  );

  -- 2. Profiles Table (extends Auth)
  create table profiles (
    id uuid references auth.users on delete cascade primary key,
    full_name text,
    phone text,
    address text,
    role text default 'user'
  );

  -- 3. Couriers Table
  create table couriers (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text,
    vehicle text,
    status text default 'available'
  );

  -- 4. Orders Table
  create table orders (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    items jsonb not null,
    total_amount numeric not null,
    status text default 'pending',
    delivery_address text not null,
    contact_phone text not null,
    comment text,
    payment_method text default 'card',
    payment_status text default 'pending',
    assigned_courier_id bigint references couriers,
    is_rated boolean default false
  );

  -- 5. Enable RLS (Row Level Security) - Simplified for demo
  alter table dishes enable row level security;
  create policy "Public dishes access" on dishes for select using (true);
  create policy "Admin dishes insert" on dishes for insert with check (auth.uid() in (select id from profiles where role = 'admin'));
  create policy "Admin dishes update" on dishes for update using (auth.uid() in (select id from profiles where role = 'admin'));

  -- (Add similar policies for orders/profiles as needed)
*/