
import React, { useState, useEffect } from 'react';
import { supabase, MOCK_DISHES } from '../supabaseClient';
import { Order, Dish } from './types';
import { Plus, Edit2, Trash2, RefreshCw, AlertTriangle, Database, Copy, CheckCircle2, ShieldAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import Modal from '../components/ui/Modal';

const SQL_SCHEMA = `-- 1. ТАБЛИЦА ПРОФИЛЕЙ
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  phone text,
  address text,
  role text default 'user'
);

-- 2. ТАБЛИЦА БЛЮД
create table if not exists public.dishes (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  image text,
  description text,
  available boolean default true
);

-- 3. ТАБЛИЦА ЗАКАЗОВ
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  items jsonb not null,
  total_amount numeric not null,
  status text default 'pending',
  delivery_address text not null,
  contact_phone text not null,
  comment text,
  payment_method text default 'card',
  payment_status text default 'pending'
);

-- 4. АВТОМАТИЧЕСКИЙ ТРИГГЕР (ИСПРАВЛЯЕТ ОШИБКУ 500 ПРИ РЕГИСТРАЦИИ)
-- Этот код заставляет базу данных саму создавать профиль при появлении нового юзера
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Удаляем старый триггер если был и ставим новый
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. НАСТРОЙКА БЕЗОПАСНОСТИ (RLS)
alter table public.dishes enable row level security;
create policy "Allow public read dishes" on public.dishes for select using (true);
create policy "Allow admins to manage dishes" on public.dishes for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

alter table public.profiles enable row level security;
create policy "Users can manage own profile" on public.profiles for all using (auth.uid() = id);

alter table public.orders enable row level security;
create policy "Users can manage own orders" on public.orders for all using (auth.uid() = user_id);
create policy "Admins view all orders" on public.orders for select using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);`;

const Admin: React.FC = () => {
  const { isAdmin } = useAuth();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<'stats' | 'orders' | 'menu' | 'db'>('stats');
  const [orders, setOrders] = useState<Order[]>([]);
  const [dishes, setDishes] = useState<Dish[]>([]);
  const [isSyncing, setIsSyncing] = useState(false);
  const [dbError, setDbError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [dbStatus, setDbStatus] = useState<any>({});

  // Menu Modal State
  const [isDishModalOpen, setIsDishModalOpen] = useState(false);
  const [editingDish, setEditingDish] = useState<Partial<Dish>>({});
  
  useEffect(() => {
    if (isAdmin) {
        loadAllData();
        checkDatabase();
    }
  }, [isAdmin]);

  const checkDatabase = async () => {
    const tables = ['profiles', 'dishes', 'orders'];
    const status: any = {};
    for (const table of tables) {
        const { error } = await supabase.from(table).select('count', { count: 'exact', head: true });
        status[table] = !error;
    }
    setDbStatus(status);
  };

  const loadAllData = async () => {
    setIsSyncing(true);
    setDbError(null);
    try {
        const { data: dbOrders, error: ordErr } = await supabase.from('orders').select('*').order('created_at', { ascending: false });
        if (ordErr) throw ordErr;
        setOrders(dbOrders as any || []);

        const { data: dbDishes, error: dishErr } = await supabase.from('dishes').select('*').order('id', { ascending: true });
        if (dishErr) throw dishErr;
        setDishes(dbDishes || []);
    } catch (err: any) {
        setDbError(err.message);
        setDishes(MOCK_DISHES);
    }
    setIsSyncing(false);
  };

  const handleCopySQL = () => {
    navigator.clipboard.writeText(SQL_SCHEMA);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const saveDish = async () => {
    setIsSyncing(true);
    try {
      const dishData = { ...editingDish };
      if (dishData.id) {
        const { error } = await supabase
          .from('dishes')
          .update(dishData)
          .eq('id', dishData.id);
        if (error) throw error;
      } else {
        delete dishData.id;
        const { error } = await supabase
          .from('dishes')
          .insert([dishData]);
        if (error) throw error;
      }
      setIsDishModalOpen(false);
      await loadAllData();
    } catch (err: any) {
      alert('Ошибка при сохранении: ' + err.message);
    }
    setIsSyncing(false);
  };

  if (!isAdmin) {
    return (
      <div className="text-center py-20 bg-white rounded-3xl m-4 shadow-xl border border-amber-100">
        <h2 className="text-3xl font-black text-amber-900">403</h2>
        <p className="text-gray-500 mt-2">Доступ разрешен только администраторам</p>
        <div className="mt-8 p-6 bg-amber-50 rounded-2xl inline-block text-left max-w-sm border border-amber-100">
           <p className="text-xs text-amber-800 leading-relaxed font-medium">
             <b>Важно для владельца:</b> Если вы видите это сообщение, значит ваша роль в базе — <code>user</code>.<br/><br/>
             Зайдите в <b>Supabase SQL Editor</b> и выполните:<br/>
             <code className="bg-white px-2 py-1 rounded block mt-2 border border-amber-200">update profiles set role = 'admin' where full_name = 'Ваше Имя';</code>
           </p>
        </div>
        <br/>
        <button onClick={() => navigate('/')} className="mt-6 bg-amber-900 text-white px-8 py-3 rounded-2xl font-bold transition hover:bg-amber-800">На главную</button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* DB Warning Header */}
      {(!dbStatus.profiles || !dbStatus.dishes) && (
          <div className="bg-red-600 text-white p-4 rounded-2xl flex items-center justify-between shadow-lg shadow-red-200 animate-pulse">
              <div className="flex items-center gap-3">
                  <ShieldAlert size={24} />
                  <span className="font-bold text-sm">Внимание! Таблицы базы данных не найдены. Приложение работает в демо-режиме.</span>
              </div>
              <button onClick={() => setActiveTab('db')} className="bg-white text-red-600 px-4 py-1.5 rounded-xl font-black text-xs uppercase">Исправить</button>
          </div>
      )}

      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-2 rounded-3xl shadow-sm border border-amber-50">
        <h1 className="text-2xl font-black text-amber-950 px-4 flex items-center gap-3">
            Админ-центр
            {isSyncing && <RefreshCw className="animate-spin text-amber-600" size={20} />}
        </h1>
        <div className="flex gap-1 overflow-x-auto no-scrollbar w-full md:w-auto">
            {['stats', 'orders', 'menu', 'db'].map(tab => (
                <button
                    key={tab}
                    onClick={() => setActiveTab(tab as any)}
                    className={`px-6 py-2 rounded-2xl text-xs font-black uppercase tracking-tight transition-all whitespace-nowrap ${activeTab === tab ? 'bg-amber-900 text-white shadow-lg transform scale-105' : 'text-gray-400 hover:text-amber-900 hover:bg-amber-50'}`}
                >
                    {tab === 'stats' ? 'Дашборд' : tab === 'orders' ? 'Заказы' : tab === 'menu' ? 'Меню' : 'База данных'}
                </button>
            ))}
        </div>
      </div>

      {activeTab === 'db' && (
          <div className="space-y-6 animate-in slide-in-from-bottom-4">
              <div className="bg-white border-2 border-amber-100 p-8 rounded-[2.5rem] shadow-lg">
                  <div className="flex items-center gap-4 text-amber-900 mb-6">
                      <div className="bg-amber-100 p-3 rounded-2xl">
                        <Database size={32} />
                      </div>
                      <div>
                        <h2 className="text-2xl font-black">Настройка Supabase</h2>
                        <p className="text-sm text-amber-600 font-medium italic">Решение ошибки 500 и «Database error saving new user»</p>
                      </div>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
                      {['profiles', 'dishes', 'orders'].map(table => (
                          <div key={table} className={`p-4 rounded-2xl border-2 flex items-center justify-between ${dbStatus[table] ? 'border-green-100 bg-green-50' : 'border-red-100 bg-red-50'}`}>
                              <span className="font-bold text-sm capitalize">{table}</span>
                              {dbStatus[table] ? <CheckCircle2 className="text-green-500" size={20} /> : <ShieldAlert className="text-red-500" size={20} />}
                          </div>
                      ))}
                  </div>

                  <div className="bg-gray-900 text-gray-300 p-6 rounded-3xl relative overflow-hidden">
                      <div className="flex justify-between items-center mb-4">
                        <p className="text-xs font-black uppercase tracking-widest text-gray-500">SQL Скрипт (Таблицы + Триггеры)</p>
                        <button 
                            onClick={handleCopySQL}
                            className="bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded-xl transition flex items-center gap-2 text-xs font-bold"
                        >
                            {copied ? <CheckCircle2 size={16} className="text-green-400" /> : <Copy size={16} />}
                            {copied ? 'Скопировано!' : 'Копировать всё'}
                        </button>
                      </div>
                      <pre className="text-[10px] overflow-x-auto max-h-60 no-scrollbar opacity-80 leading-relaxed font-mono">
                          {SQL_SCHEMA}
                      </pre>
                  </div>

                  <div className="mt-8 flex gap-4">
                      <button onClick={checkDatabase} className="bg-amber-50 text-amber-900 px-6 py-3 rounded-2xl font-bold border border-amber-100 hover:bg-amber-100 transition">
                          Проверить таблицы снова
                      </button>
                      <a href="https://app.supabase.com/" target="_blank" className="flex-1 bg-amber-950 text-white text-center py-3 rounded-2xl font-bold hover:opacity-90 transition">
                          Открыть Supabase Dashboard
                      </a>
                  </div>
              </div>
          </div>
      )}

      {activeTab === 'menu' && (
          <div className="space-y-6 animate-in slide-in-from-bottom-4">
              <div className="flex justify-between items-center bg-white p-4 rounded-2xl border border-amber-50 shadow-sm">
                  <p className="text-gray-500 text-sm font-medium italic">Управление меню</p>
                  <button onClick={() => { setEditingDish({category: 'main'}); setIsDishModalOpen(true); }} className="bg-amber-900 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-amber-800 transition shadow-md">
                      <Plus size={20} /> Новое блюдо
                  </button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {dishes.map(dish => (
                      <div key={dish.id} className={`bg-white p-4 rounded-2xl border border-amber-50 shadow-sm flex flex-col justify-between transition-all hover:shadow-md ${!dish.available ? 'bg-gray-50/80 grayscale opacity-70' : ''}`}>
                          <div className="flex gap-4">
                              <img src={dish.image} className="w-24 h-24 object-cover rounded-2xl shadow-inner bg-gray-100" />
                              <div className="flex-1">
                                  <h3 className="font-black text-amber-950 text-lg leading-tight">{dish.name}</h3>
                                  <p className="text-[10px] text-amber-700 font-black uppercase tracking-widest mt-1">{dish.category}</p>
                                  <p className="text-xl font-black text-gray-900 mt-2">{dish.price} ₽</p>
                              </div>
                          </div>
                          
                          <div className="flex gap-2 mt-4 pt-4 border-t border-amber-50">
                              <button 
                                onClick={async () => {
                                    setIsSyncing(true);
                                    await supabase.from('dishes').update({ available: !dish.available }).eq('id', dish.id);
                                    await loadAllData();
                                }}
                                className={`flex-1 py-2.5 rounded-xl text-xs font-black uppercase tracking-tight transition-all ${dish.available ? 'bg-green-50 text-green-700 border border-green-100 hover:bg-green-100' : 'bg-red-600 text-white shadow-lg shadow-red-100 hover:bg-red-700'}`}
                              >
                                  {dish.available ? 'В меню' : 'В Стоп-листе'}
                              </button>
                              <button onClick={() => { setEditingDish(dish); setIsDishModalOpen(true); }} className="p-2.5 bg-gray-50 text-gray-400 rounded-xl hover:text-amber-900 hover:bg-amber-50 transition"><Edit2 size={18} /></button>
                              <button onClick={async () => { if(confirm('Удалить блюдо?')) { await supabase.from('dishes').delete().eq('id', dish.id); await loadAllData(); } }} className="p-2.5 bg-gray-50 text-gray-400 rounded-xl hover:text-red-600 hover:bg-red-50 transition"><Trash2 size={18} /></button>
                          </div>
                      </div>
                  ))}
              </div>
          </div>
      )}

      {activeTab === 'orders' && (
          <div className="bg-white rounded-3xl shadow-sm border border-amber-50 overflow-hidden animate-in slide-in-from-bottom-4">
              <table className="w-full text-left">
                  <thead className="bg-amber-50/50 text-amber-900 text-[10px] font-black uppercase tracking-widest">
                      <tr>
                          <th className="p-6">Заказ</th>
                          <th className="p-6">Клиент</th>
                          <th className="p-6">Сумма</th>
                          <th className="p-6">Статус</th>
                      </tr>
                  </thead>
                  <tbody className="divide-y divide-amber-50">
                      {orders.map(order => (
                          <tr key={order.id} className="hover:bg-amber-50/10 transition">
                              <td className="p-6 font-black text-amber-950">#{order.id}</td>
                              <td className="p-6">
                                  <div className="font-bold text-gray-800">{order.contact_phone}</div>
                                  <div className="text-[10px] text-gray-400 mt-0.5 uppercase font-medium">{order.delivery_address}</div>
                              </td>
                              <td className="p-6 font-black text-amber-800">{order.total_amount} ₽</td>
                              <td className="p-6">
                                  <select 
                                      className="bg-white border border-amber-100 rounded-xl text-[11px] font-black uppercase p-2 outline-none shadow-sm cursor-pointer hover:border-amber-300 transition"
                                      value={order.status}
                                      onChange={async (e) => {
                                          await supabase.from('orders').update({status: e.target.value}).eq('id', order.id);
                                          loadAllData();
                                      }}
                                  >
                                      <option value="pending">Ожидание</option>
                                      <option value="cooking">Готовится</option>
                                      <option value="delivering">Доставка</option>
                                      <option value="delivered">Готово</option>
                                  </select>
                              </td>
                          </tr>
                      ))}
                  </tbody>
              </table>
              {orders.length === 0 && <div className="p-24 text-center text-gray-400 font-medium italic">Заказов пока нет</div>}
          </div>
      )}

      {activeTab === 'stats' && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-in slide-in-from-bottom-4">
              <div className="bg-white p-8 rounded-3xl border border-amber-50 shadow-sm border-b-4 border-b-amber-900">
                  <h4 className="text-gray-400 text-[10px] font-black uppercase tracking-widest mb-2">Всего заказов</h4>
                  <p className="text-4xl font-black text-amber-950">{orders.length}</p>
              </div>
              <div className="bg-white p-8 rounded-3xl border border-amber-50 shadow-sm border-b-4 border-b-orange-400">
                  <h4 className="text-gray-400 text-[10px] font-black uppercase tracking-widest mb-2">Блюд в меню</h4>
                  <p className="text-4xl font-black text-amber-950">{dishes.length}</p>
              </div>
              <div className="bg-white p-8 rounded-3xl border border-amber-50 shadow-sm border-b-4 border-b-green-500">
                  <h4 className="text-gray-400 text-[10px] font-black uppercase tracking-widest mb-2">Выручка</h4>
                  <p className="text-4xl font-black text-green-700">{orders.reduce((acc, o) => acc + o.total_amount, 0)} ₽</p>
              </div>
          </div>
      )}

      <Modal isOpen={isDishModalOpen} onClose={() => setIsDishModalOpen(false)} title={editingDish.id ? 'Изменить блюдо' : 'Новое блюдо'}>
          <div className="space-y-4">
              <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-gray-400 ml-1">Название</label>
                  <input className="w-full p-4 bg-gray-50 border-none rounded-2xl outline-none focus:ring-2 ring-amber-500 transition" value={editingDish.name || ''} onChange={e => setEditingDish({...editingDish, name: e.target.value})} />
              </div>
              <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-gray-400 ml-1">Категория</label>
                  <select className="w-full p-4 bg-gray-50 border-none rounded-2xl outline-none focus:ring-2 ring-amber-500 transition" value={editingDish.category} onChange={e => setEditingDish({...editingDish, category: e.target.value as any})}>
                      <option value="main">Основные</option>
                      <option value="soups">Супы</option>
                      <option value="salads">Салаты</option>
                      <option value="drinks">Напитки</option>
                      <option value="desserts">Десерты</option>
                  </select>
              </div>
              <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-gray-400 ml-1">Цена (₽)</label>
                  <input type="number" className="w-full p-4 bg-gray-50 border-none rounded-2xl outline-none focus:ring-2 ring-amber-500 transition" value={editingDish.price || ''} onChange={e => setEditingDish({...editingDish, price: Number(e.target.value)})} />
              </div>
              <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-gray-400 ml-1">URL фото</label>
                  <input className="w-full p-4 bg-gray-50 border-none rounded-2xl outline-none focus:ring-2 ring-amber-500 transition" value={editingDish.image || ''} onChange={e => setEditingDish({...editingDish, image: e.target.value})} />
              </div>
              <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-gray-400 ml-1">Описание</label>
                  <textarea className="w-full p-4 bg-gray-50 border-none rounded-2xl outline-none h-24 focus:ring-2 ring-amber-500 transition" value={editingDish.description || ''} onChange={e => setEditingDish({...editingDish, description: e.target.value})} />
              </div>
              <button onClick={saveDish} className="w-full bg-amber-900 text-white py-4 rounded-2xl font-bold shadow-lg hover:bg-amber-800 transition transform active:scale-95 mt-4">
                  Сохранить
              </button>
          </div>
      </Modal>
    </div>
  );
};

export default Admin;
