
import React, { useState, useEffect } from 'react';
import { supabase, MOCK_DISHES } from '../supabaseClient';
import { Order, Dish } from './types';
import { Plus, Edit2, Trash2, RefreshCw, AlertTriangle, Database, Copy, CheckCircle2, ShieldAlert } from 'lucide-react';
// Correctly import useNavigate from react-router-dom
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import Modal from '../components/ui/Modal';

const SQL_SCHEMA = `-- 1. ТАБЛИЦА ПРОФИЛЕЙ
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  phone text unique,
  address text,
  role text default 'user'
);

-- Индекс для поиска по телефону
create index if not exists profiles_phone_idx on public.profiles (phone);

-- 2. ТАБЛИЦА БЛЮД
create table if not exists public.dishes (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  image text,
  description text,
  available boolean default true
);

-- 3. ТАБЛИЦА ЗАКАЗОВ
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  items jsonb not null,
  total_amount numeric not null,
  status text default 'pending',
  delivery_address text not null,
  contact_phone text not null,
  comment text,
  payment_method text default 'card',
  payment_status text default 'pending'
);

-- 4. ИСПРАВЛЕННЫЙ ТРИГГЕР ДЛЯ НОВОГО ПРОЕКТА
create or replace function public.handle_new_user()
returns trigger as $$
declare
  user_phone text;
begin
  user_phone := new.raw_user_meta_data->>'phone';
  if user_phone = '' then
    user_phone := null;
  end if;

  insert into public.profiles (id, full_name, phone, role)
  values (
    new.id, 
    coalesce(new.raw_user_meta_data->>'full_name', ''), 
    user_phone,
    'user'
  )
  on conflict (id) do update 
  set 
    full_name = excluded.full_name,
    phone = coalesce(excluded.phone, profiles.phone);

  return new;
exception when others then
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. ПРАВИЛА БЕЗОПАСНОСТИ (RLS)
alter table public.dishes enable row level security;
create policy "Public read dishes" on public.dishes for select using (true);
create policy "Admins manage dishes" on public.dishes for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

alter table public.profiles enable row level security;
create policy "Profiles view/edit" on public.profiles for all using (auth.uid() = id);

alter table public.orders enable row level security;
create policy "Orders manage" on public.orders for all using (auth.uid() = user_id);
create policy "Admins orders" on public.orders for select using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);`;

const Admin: React.FC = () => {
  const { isAdmin, user: currentUser } = useAuth();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<'stats' | 'orders' | 'menu' | 'db'>('stats');
  const [orders, setOrders] = useState<Order[]>([]);
  const [dishes, setDishes] = useState<Dish[]>([]);
  const [isSyncing, setIsSyncing] = useState(false);
  const [dbError, setDbError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [dbStatus, setDbStatus] = useState<any>({});

  const [isDishModalOpen, setIsDishModalOpen] = useState(false);
  const [editingDish, setEditingDish] = useState<Partial<Dish>>({});
  
  useEffect(() => {
    if (isAdmin) {
        loadAllData();
        checkDatabase();
    }
  }, [isAdmin]);

  const checkDatabase = async () => {
    const tables = ['profiles', 'dishes', 'orders'];
    const status: any = {};
    for (const table of tables) {
        const { error } = await supabase.from(table).select('count', { count: 'exact', head: true });
        status[table] = !error;
    }
    setDbStatus(status);
  };

  const loadAllData = async () => {
    setIsSyncing(true);
    setDbError(null);
    try {
        const { data: dbOrders, error: ordErr } = await supabase.from('orders').select('*').order('created_at', { ascending: false });
        if (ordErr) throw ordErr;
        setOrders(dbOrders as any || []);

        const { data: dbDishes, error: dishErr } = await supabase.from('dishes').select('*').order('id', { ascending: true });
        if (dishErr) throw dishErr;
        setDishes(dbDishes || []);
    } catch (err: any) {
        setDbError(err.message);
        setDishes(MOCK_DISHES);
    }
    setIsSyncing(false);
  };

  const handleCopySQL = () => {
    navigator.clipboard.writeText(SQL_SCHEMA);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const saveDish = async () => {
    setIsSyncing(true);
    try {
      const dishData = { ...editingDish };
      if (dishData.id) {
        const { error } = await supabase.from('dishes').update(dishData).eq('id', dishData.id);
        if (error) throw error;
      } else {
        delete dishData.id;
        const { error } = await supabase.from('dishes').insert([dishData]);
        if (error) throw error;
      }
      setIsDishModalOpen(false);
      await loadAllData();
    } catch (err: any) {
      alert('Ошибка при сохранении: ' + err.message);
    }
    setIsSyncing(false);
  };

  if (!isAdmin) {
    return (
      <div className="text-center py-20 bg-white rounded-3xl m-4 shadow-xl border border-amber-100">
        <h2 className="text-3xl font-black text-amber-900">403</h2>
        <p className="text-gray-500 mt-2 font-medium">Доступ только для администрации</p>
        <div className="mt-8 p-6 bg-amber-50 rounded-2xl inline-block text-left max-w-sm border border-amber-100">
           <p className="text-xs text-amber-800 leading-relaxed font-medium">
             <b>Инструкция для нового проекта:</b><br/>
             1. Выполните SQL-скрипт в панели Supabase.<br/>
             2. Выполните команду:<br/>
             <code className="bg-white px-2 py-1 rounded block mt-2 border border-amber-200 text-[10px] break-all">update profiles set role = 'admin' where id = '{currentUser?.id || 'ВАШ_ID'}';</code>
           </p>
        </div>
        <br/>
        <button onClick={() => navigate('/')} className="mt-6 bg-amber-900 text-white px-8 py-3 rounded-2xl font-bold transition hover:bg-amber-800">На главную</button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {(!dbStatus.profiles || !dbStatus.dishes) && (
          <div className="bg-red-600 text-white p-4 rounded-2xl flex items-center justify-between shadow-lg animate-pulse">
              <div className="flex items-center gap-3">
                  <ShieldAlert size={24} />
                  <span className="font-bold text-sm">База данных требует настройки SQL на новом проекте!</span>
              </div>
              <button onClick={() => setActiveTab('db')} className="bg-white text-red-600 px-4 py-1.5 rounded-xl font-black text-xs uppercase">Исправить</button>
          </div>
      )}

      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-2 rounded-3xl shadow-sm border border-amber-50">
        <h1 className="text-2xl font-black text-amber-950 px-4 flex items-center gap-3">
            Админ-центр
            {isSyncing && <RefreshCw className="animate-spin text-amber-600" size={20} />}
        </h1>
        <div className="flex gap-1 overflow-x-auto no-scrollbar w-full md:w-auto">
            {['stats', 'orders', 'menu', 'db'].map(tab => (
                <button
                    key={tab}
                    onClick={() => setActiveTab(tab as any)}
                    className={`px-6 py-2 rounded-2xl text-xs font-black uppercase tracking-tight transition-all whitespace-nowrap ${activeTab === tab ? 'bg-amber-900 text-white shadow-lg transform scale-105' : 'text-gray-400 hover:text-amber-900 hover:bg-amber-50'}`}
                >
                    {tab === 'stats' ? 'Дашборд' : tab === 'orders' ? 'Заказы' : tab === 'menu' ? 'Меню' : 'Настройка БД'}
                </button>
            ))}
        </div>
      </div>

      {activeTab === 'db' && (
          <div className="space-y-6 animate-in slide-in-from-bottom-4">
              <div className="bg-white border-2 border-amber-100 p-8 rounded-[2.5rem] shadow-lg">
                  <div className="flex items-center gap-4 text-amber-900 mb-6">
                      <div className="bg-amber-100 p-3 rounded-2xl">
                        <Database size={32} />
                      </div>
                      <div>
                        <h2 className="text-2xl font-black">Новый проект Supabase</h2>
                        <p className="text-sm text-amber-600 font-medium italic">Выполните этот код для создания таблиц</p>
                      </div>
                  </div>

                  <div className="bg-gray-900 text-gray-300 p-6 rounded-3xl relative overflow-hidden">
                      <div className="flex justify-between items-center mb-4">
                        <p className="text-xs font-black uppercase tracking-widest text-gray-500">SQL Скрипт (Ultimate)</p>
                        <button 
                            onClick={handleCopySQL}
                            className="bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded-xl transition flex items-center gap-2 text-xs font-bold"
                        >
                            {copied ? <CheckCircle2 size={16} className="text-green-400" /> : <Copy size={16} />}
                            {copied ? 'Скопировано!' : 'Копировать всё'}
                        </button>
                      </div>
                      <pre className="text-[10px] overflow-x-auto max-h-60 no-scrollbar opacity-80 leading-relaxed font-mono">
                          {SQL_SCHEMA}
                      </pre>
                  </div>
              </div>
          </div>
      )}

      {activeTab === 'stats' && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-in slide-in-from-bottom-4">
              <div className="bg-white p-8 rounded-3xl border border-amber-50 shadow-sm border-b-4 border-b-amber-900">
                  <h4 className="text-gray-400 text-[10px] font-black uppercase tracking-widest mb-2">Всего заказов</h4>
                  <p className="text-4xl font-black text-amber-950">{orders.length}</p>
              </div>
              <div className="bg-white p-8 rounded-3xl border border-amber-50 shadow-sm border-b-4 border-b-orange-400">
                  <h4 className="text-gray-400 text-[10px] font-black uppercase tracking-widest mb-2">Блюд в меню</h4>
                  <p className="text-4xl font-black text-amber-950">{dishes.length}</p>
              </div>
              <div className="bg-white p-8 rounded-3xl border border-amber-50 shadow-sm border-b-4 border-b-green-500">
                  <h4 className="text-gray-400 text-[10px] font-black uppercase tracking-widest mb-2">Выручка</h4>
                  <p className="text-4xl font-black text-green-700">{orders.reduce((acc, o) => acc + o.total_amount, 0)} ₽</p>
              </div>
          </div>
      )}

      {/* Отрисовка Меню и Заказов аналогично предыдущей версии */}
      {activeTab === 'menu' && (
          <div className="space-y-6 animate-in slide-in-from-bottom-4">
              <div className="flex justify-between items-center bg-white p-4 rounded-2xl border border-amber-50 shadow-sm">
                  <p className="text-gray-500 text-sm font-medium italic">Управление меню</p>
                  <button onClick={() => { setEditingDish({category: 'main'}); setIsDishModalOpen(true); }} className="bg-amber-900 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-amber-800 transition shadow-md">
                      <Plus size={20} /> Новое блюдо
                  </button>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {dishes.map(dish => (
                      <div key={dish.id} className="bg-white p-4 rounded-2xl border border-amber-50 shadow-sm flex flex-col justify-between transition-all hover:shadow-md">
                          <div className="flex gap-4">
                              <img src={dish.image} className="w-24 h-24 object-cover rounded-2xl shadow-inner bg-gray-100" />
                              <div className="flex-1">
                                  <h3 className="font-black text-amber-950 text-lg leading-tight">{dish.name}</h3>
                                  <p className="text-[10px] text-amber-700 font-black uppercase tracking-widest mt-1">{dish.category}</p>
                                  <p className="text-xl font-black text-gray-900 mt-2">{dish.price} ₽</p>
                              </div>
                          </div>
                          <div className="flex gap-2 mt-4 pt-4 border-t border-amber-50">
                              <button onClick={() => { setEditingDish(dish); setIsDishModalOpen(true); }} className="p-2.5 bg-gray-50 text-gray-400 rounded-xl hover:text-amber-900 transition"><Edit2 size={18} /></button>
                              <button onClick={async () => { if(confirm('Удалить?')) { await supabase.from('dishes').delete().eq('id', dish.id); await loadAllData(); } }} className="p-2.5 bg-gray-50 text-gray-400 rounded-xl hover:text-red-600 transition"><Trash2 size={18} /></button>
                          </div>
                      </div>
                  ))}
              </div>
          </div>
      )}
      
      <Modal isOpen={isDishModalOpen} onClose={() => setIsDishModalOpen(false)} title={editingDish.id ? 'Изменить блюдо' : 'Новое блюдо'}>
          <div className="space-y-4">
              <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-gray-400 ml-1">Название</label>
                  <input className="w-full p-4 bg-gray-50 border-none rounded-2xl outline-none" value={editingDish.name || ''} onChange={e => setEditingDish({...editingDish, name: e.target.value})} />
              </div>
              <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-gray-400 ml-1">Цена (₽)</label>
                  <input type="number" className="w-full p-4 bg-gray-50 border-none rounded-2xl outline-none" value={editingDish.price || ''} onChange={e => setEditingDish({...editingDish, price: Number(e.target.value)})} />
              </div>
              <button onClick={saveDish} className="w-full bg-amber-900 text-white py-4 rounded-2xl font-bold shadow-lg hover:bg-amber-800 transition">
                  Сохранить
              </button>
          </div>
      </Modal>
    </div>
  );
};

export default Admin;
